import Head from 'next/head';
import Header from '../components/header';
import Banner from '../components/banner';
import Nav from '../components/navmenu';
import Key from '../components/key-features';
import Services from '../components/services';
import Features from '../components/feature';
import Product from '../components/product';
import Pricing from '../components/pricing';
import Team from '../components/team';
import Testimonial from '../components/testimonial';
import Footer from '../components/footer';
import React, { useState } from 'react';



export default function Home() {
  const [isMonthly, setPeriod] = useState(true);
  return (
    <div className='w-screen overflow-hidden flex  bigtablet:block'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <div className='navBar bg-white fixed top-0 bigtablet:hidden z-50 h-screen' id='barContent'>
        <Nav/>
      </div>
    <div className=' overflow-y-scroll w-full overflow-x-hidden block '>
      <div className='fixed top-0 z-40'>
      <Header/>
      </div>
  <div className='mt-20'>
  <Banner/>
  <div name="Features" >
<Key/>
<Services/>
<Features/>
<Product/>
</div>
<Pricing isMonthly={isMonthly}
setPeriod={setPeriod}/>
<Team/>
<Testimonial/>
  </div>
  <Footer/>
  </div> 
    </div>
  )
}
